spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 475108374000-tod1dtrnnpovd2d2uqi01p3duug48nfu.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            client-id: 2d0374fbd289c522bf3c
            client-secret: 720d1fe538c4a63972567f1072121d493830e21c
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user