gateway:
  routes:
    - id: authService
      uri: 'http://localhost:8081'
      predicates:
        - '/api/auth'
      pathRewrite:
        - '^/api/auth, /auth'
    - id: userService
      uri: 'http://localhost:8082'
      predicates:
        - '/api/user'
