version: "3.8"
services:
#  nginx:
#    image: nginx:alpine
#    restart: always
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#      - ./docker/nginx/customConfig.conf:/etc/nginx/conf.d/customConfig.conf
#  common-service:
#    platform: linux/x86_64
#    build:
#      context: ./common
#  authorization-server-service:
#    platform: linux/x86_64
#    build:
#      context: ./authorizationServer
#    ports:
#      - 9000:9000
#    depends_on:
#      - common-service
#      - db-mysql
#  store-frontend-service:
#    build:
#      context: ./storeFrontend
#    ports:
#      - 3000:3000


  db-mysql:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/database/mysql/init:/docker-entrypoint-initdb.d
volumes:
  mysql:
networks:
  dienmaykimkhi:
    driver: bridge