spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 475108374000-tod1dtrnnpovd2d2uqi01p3duug48nfu.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
#              - openid
              - email
              - profile
          github:
            client-id: 2d0374fbd289c522bf3c
            client-secret: 87fd66a81d3694e5d8d95db8d34351a4c2cac787
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
#              - openid
              - user:email
              - read:user