CREATE DATABASE IF NOT EXISTS authService;
CREATE DATABASE IF NOT EXISTS productService;
CREATE DATABASE IF NOT EXISTS cartService;
CREATE DATABASE IF NOT EXISTS orderService;
CREATE DATABASE IF NOT EXISTS inventoryService;
CREATE DATABASE IF NOT EXISTS mediaService;
CREATE DATABASE IF NOT EXISTS ratingService;

