spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
properties:
  product-service-url: http://localhost:8082/api/v1
  media-service-url: http://localhost:8083/api/v1
  inventories-service-url: http://localhost:8085/api/v1
  promotion-service-url: http://localhost:8089/api/v1
